### ISSUE TITLE
Challonge community issues

### ISSUE THREAD

**Issue by AlphaKretin** [DawnbrandBots/emcee-tournament-bot#41]
If a tournament is relocated to a challonge community, even if Emcee owns that community, it can no longer access the tournament by the API.

**Comment by kevinlul** [comment]
Escalated to Challonge help desk.

**Comment by kevinlul** [comment]
You can list all tournaments filed under a community by providing the `subdomain` querystring parameter to the [list tournaments endpoint](https://api.challonge.com/v1/documents/tournaments/index).

This subdomain is obtained as the owner or admin of a community by reading it off the settings https://challonge.com/communities/PERMALINK/community_settings/edit and works even without PRO. It is NOT the same as the permalink.

The per-tournament endpoints will work if the `{tournament}` object being accessed in the URL is of the form `:subdomain-:tournament_url` according to documentation.

Thus, the community can also be programmatically modified by providing the `tournament[subdomain]` field to the [update endpoint](https://api.challonge.com/v1/documents/tournaments/update) if the authenticating user has write access.

Questions:
- is write access being a collaborator or is admin access required?
- is accepting an invite to the community a manual, automatic, or programmatic process?

**Comment by kevinlul** [comment]
Read is public so bots do not need to be a collaborator to read info about tournaments in a community (list or show individual)
```json
curl https://CREDENTIALS@api.challonge.com/v1/tournaments.json?subdomain=f12f7025fbd9137350f71ca3
[{"tournament":{"id":8718244,"name":"sydney","url":"ignis_sydney","description":"","tournament_type":"swiss","started_at":null,"completed_at":null,"require_score_agreement":false,"notify_users_when_matches_open":true,"created_at":"2020-07-24T00:01:12.578-03:00","updated_at":"2020-07-24T00:01:12.578-03:00","state":"pending","open_signup":false,"notify_users_when_the_tournament_ends":true,"progress_meter":0,"quick_advance":false,"hold_third_place_match":false,"pts_for_game_win":"0.0","pts_for_game_tie":"0.0","pts_for_match_win":"1.0","pts_for_match_tie":"0.5","pts_for_bye":"1.0","swiss_rounds":0,"private":false,"ranked_by":"match wins","show_rounds":true,"hide_forum":false,"sequential_pairings":false,"accept_attachments":false,"rr_pts_for_game_win":"0.0","rr_pts_for_game_tie":"0.0","rr_pts_for_match_win":"1.0","rr_pts_for_match_tie":"0.5","created_by_api":false,"credit_capped":false,"category":null,"hide_seeds":false,"prediction_method":0,"predictions_opened_at":null,"anonymous_voting":false,"max_predictions_per_user":1,"signup_cap":null,"game_id":45,"participants_count":0,"group_stages_enabled":false,"allow_participant_match_reporting":true,"teams":false,"check_in_duration":null,"start_at":null,"started_checking_in_at":null,"tie_breaks":["match wins vs tied","median buchholz","points difference"],"locked_at":null,"event_id":null,"public_predictions_before_start_time":false,"ranked":true,"grand_finals_modifier":null,"predict_the_losers_bracket":false,"spam":null,"ham":null,"rr_iterations":1,"tournament_registration_id":null,"donation_contest_enabled":null,"mandatory_donation":null,"non_elimination_tournament_data":{"participants_per_match":""},"auto_assign_stations":null,"only_start_matches_with_stations":null,"registration_fee":"0.0","registration_type":"free","split_participants":false,"allowed_regions":null,"description_source":"","subdomain":null,"full_challonge_url":"https://challonge.com/ignis_sydney","live_image_url":"https://challonge.com/ignis_sydney.svg","sign_up_url":null,"review_before_finalizing":true,"accepting_predictions":false,"participants_locked":false,"game_name":"Yu-Gi-Oh!","participants_swappable":true,"team_convertable":false,"group_stages_were_started":false}}]
```

**Comment by kevinlul** [comment]
The account must accept an invite to have write permissions, or the response body will be
```json
{"errors":["You only have read access to this tournament"]}
```

**Comment by kevinlul** [comment]
Without admin permissions, changing the name is allowed but deleting the tournament is not allowed.

**Comment by kevinlul** [comment]
See #395, almost certainly not putting more effort into Challonge integrations.
