### ISSUE TITLE
Screenshot collection

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/emcee-tournament-bot#442]
Acceptance criteria: collect attachments from DMs and forward to private channel

**Comment by AlphaKretin** [comment]
If the original source post for an image is deleted, the image is after some time flushed from Discord's CDN and the URL will no longer be valid. This is the primary issue to solve here. 

One solution would be to accept this, and warn users not to delete their submissions, while teaching TOs to treat missing deck images as an attempt to dodge deck checks (i.e. cheating). This relies on user trust to a degree, but with recourse for those who ignore instructions.

Alternatively, we could rehost the images somewhere out of the user's sight. This is more solid, but requires all the overhead you'd expect, which makes it an unappealing option in my opinion.

**Comment by AlphaKretin** [comment]
Current PR #450 tentatively assumes the former approach (warning players), but this can be changed before that PR is finalised.
