### ISSUE TITLE
/drop: authenticatePlayer failure interacts poorly with deferReply

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/emcee-tournament-bot#496]
## Expected behaviour

Player not in the tournament receives an appropriate reply to `/drop`.

### Actual behaviour

![image](https://user-images.githubusercontent.com/6320810/219805444-3433d8b9-08d9-4ac4-ac25-7eb39ba9ac8e.png)

```
Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
bot_1         |     at ChatInputCommandInteraction.reply (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:102:46)
bot_1         |     at authenticatePlayer (/src/slash/database.ts:68:21)
bot_1         |     at DropCommand.execute (/src/slash/drop.ts:41:42)
bot_1         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bot_1         |     at DropCommand.run (/src/SlashCommand.ts:44:20)
bot_1         |     at Client.interactionCreate (/src/events/interaction.ts:94:4) {
bot_1         |   code: 'InteractionAlreadyReplied'
bot_1         | }
```

### Steps to reproduce

Use `/drop` for a tournament you are not registered for.

**Comment by kevinlul** [comment]
Full resolution:
- /drop is smart like the force drop context command: tournament parameter becomes optional. Try to find the one tournament that is in progress or pending to leave.
- If the player isn't in any, tell them and that's the end of it.
- If the player is in multiple, the tournament parameter is necessary, tell them. This should be the same as force drop context.
- Now, dropPlayer

@AlphaKretin would you be able to take this?

**Comment by AlphaKretin** [comment]
Got stuff the next couple of days but I should be able to fit it in before the next week without too much trouble, feel free to remind me if I drag my feet
